#!/bin/bash
# chkconfig: 2345 20 80
# description: streams agent
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PATH=/usr/bin:/sbin:/bin:/usr/sbin
export PATH

[ -f /etc/sysconfig/streams-agent ] && . /etc/sysconfig/streams-agent
lockfile=${LOCKFILE-/var/lock/subsys/streams-agent}
streamsd=${STREAMSD-/opt/streams-agent/bin/streams.sh}
REGEX="org.streams.agent.main.Main -start agent"

RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

if [ -f /etc/profile.d/java.sh ]; then
 . /etc/profile.d/java.sh
fi

if [ -f /opt/streams-agent/conf/streams-env.sh ]; then
 . /opt/streams-agent/conf/streams-env.sh
fi

if [ -n $JAVA_HOME ]; then

  echo "JAVA_HOME not set using /usr/java/latest"
  export JAVA_HOME="/usr/java/latest"

fi


start() {

   pid=`pgrep -f "$REGEX"`

   if [ -n "$pid" ]; then
    echo "The Streams agent is already running"
    RETVAL=2
   else

    echo -n $"Starting streams agent: "
        daemon $streamsd -start agent &> /dev/null &
    RETVAL=$?
    echo
        [ $RETVAL = 0 ] && touch ${lockfile}

   fi

   return $RETVAL

}

stop() {

    pid=`pgrep -f "$REGEX"`
    if [ -n "$pid" ]; then
      echo -n $"Stopping streams: "
        $streamsd -stop agent
      RETVAL=$?
      echo
       [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
    else
       echo "No Streams agent instance is running" 
       RETVAL=2
    fi

    return $RETVAL

}

restart() {
    stop
    start
}

status() {

   pid=`pgrep -f "$REGEX"`
   if [ -n "$pid" ]; then
      echo "Streams agent is running"
      echo "$pid"
      RETVAL=1
   else
       echo "Streams agent instance is stopped" 
       RETVAL=2
   fi

   return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
        status
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
esac

exit $RETVAL

